name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r audio_downloader_requirements.txt
        pip install pyinstaller pillow
        
    - name: Create icon
      run: python create_icon.py
        
    - name: Build executable
      run: pyinstaller --onefile --windowed --icon=icon.ico --name="AudioDownloader" audio_downloader_gui.py
        
    - name: Upload executable
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AudioDownloader-Windows
        path: dist/AudioDownloader.exe
        
    - name: Create release ZIP
      run: |
        cd dist
        powershell Compress-Archive -Path "AudioDownloader.exe" -DestinationPath "AudioDownloader-Windows.zip"
        
    - name: Upload release ZIP
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AudioDownloader-Windows-ZIP
        path: dist/AudioDownloader-Windows.zip 