name: GitHub Pages Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r audio_downloader_requirements.txt
        pip install pyinstaller pillow
        
    - name: Create icon
      run: python create_icon.py
        
    - name: Build executable
      run: pyinstaller --onefile --windowed --icon=icon.ico --name="AudioDownloader" audio_downloader_gui.py
      
    # Create a ZIP file manually
    - name: Create ZIP file
      run: |
        cd dist
        powershell Compress-Archive -Path "AudioDownloader.exe" -DestinationPath "AudioDownloader.zip"
    
    # Prepare the public directory with the existing index.html
    - name: Prepare public directory
      run: |
        mkdir -p public
        copy index.html public\
        copy dist\AudioDownloader.zip public\
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true 